#!/usr/bin/env python3

"""
Generate out-of-fold coding probabilities for all ORFs and rank putative
missed or incorrectly annotated protein-coding genes.

Each genome is assigned to exactly one cross-validation fold. Predictions for
a genome are therefore generated by a model that was not trained on any ORF
from that genome.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd
from sklearn.model_selection import GroupKFold
from xgboost import XGBRFClassifier

# The documented ROCm environment installs genome_entropy from PyPI, and
# running this file by path only puts scripts/ on sys.path. Prefer the
# checkout this script lives in so the script and the package it calls into
# cannot diverge; fall back to the installed package outside a checkout.
CHECKOUT_SOURCE = Path(__file__).resolve().parent.parent / "src"
if (CHECKOUT_SOURCE / "genome_entropy").is_dir():
    sys.path.insert(0, str(CHECKOUT_SOURCE))

from genome_entropy.io.genbank import normalise_orf_interval  # noqa: E402
from genome_entropy.ml import (  # noqa: E402
    extract_features,
    filter_json_records_with_features,
    load_json_file,
)

GENOMIC_COLUMNS = [
    "input_id",
    "orf_id",
    "genomic_start",
    "genomic_end",
    "genomic_strand",
]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Rank high-confidence ORFs missing from GenBank annotations."
    )
    parser.add_argument(
        "--json-dir",
        required=True,
        type=Path,
        help="Directory containing genome_entropy JSON or JSON.GZ files.",
    )
    parser.add_argument(
        "--output-dir",
        required=True,
        type=Path,
        help="Directory for prediction and candidate tables.",
    )
    parser.add_argument(
        "--folds",
        type=int,
        default=5,
        help="Number of genome-level cross-validation folds.",
    )
    parser.add_argument(
        "--minimum-probability",
        type=float,
        default=0.80,
        help="Minimum coding probability for candidate ORFs.",
    )
    parser.add_argument(
        "--maximum-annotated-probability",
        type=float,
        default=0.50,
        help="Maximum probability for a competing annotated ORF.",
    )
    parser.add_argument(
        "--minimum-probability-difference",
        type=float,
        default=0.40,
        help="Minimum candidate-minus-annotated probability difference.",
    )
    parser.add_argument(
        "--minimum-aa-length",
        type=int,
        default=30,
        help="Minimum translated candidate length.",
    )
    parser.add_argument(
        "--device",
        choices=("cpu", "cuda"),
        default="cpu",
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=42,
    )
    return parser.parse_args()


def discover_json_files(json_dir: Path) -> list[Path]:
    files = sorted(
        {
            *json_dir.rglob("*.json"),
            *json_dir.rglob("*.json.gz"),
        }
    )

    if not files:
        raise FileNotFoundError(
            f"No .json or .json.gz files were found under {json_dir}"
        )

    return files


def load_all_records(files: list[Path]) -> list[dict[str, Any]]:
    records: list[dict[str, Any]] = []

    for number, path in enumerate(files, start=1):
        print(f"[{number:,}/{len(files):,}] Reading {path}", flush=True)

        file_records = load_json_file(path)
        usable_records = filter_json_records_with_features(file_records)
        records.extend(usable_records)

    if not records:
        raise ValueError("No genome records containing usable ORFs were found")

    return records


def collect_genomic_intervals(
    records: list[list[dict[str, Any]]],
) -> tuple[pd.DataFrame, int]:
    """Return every ORF's genomic interval, with a count of unusable ORFs.

    The serialised ``location.start``/``location.end`` values are raw
    ``get_orfs`` coordinates: one-based, inclusive, and, on the negative
    strand, indexing the reverse complement rather than the genomic axis.
    They are normalised here with the same helper the GenBank CDS matcher
    uses, so overlaps between ORFs on opposite strands are real overlaps.
    """
    rows: list[dict[str, Any]] = []
    unusable = 0

    for record_group in records:
        for record in record_group:
            features = record.get("features")
            if not isinstance(features, dict):
                # Legacy records carry no input_dna_length, so reverse-strand
                # coordinates cannot be placed on the genomic axis.
                unusable += len(record.get("orfs") or [])
                continue

            input_id = str(record.get("input_id", ""))
            record_length = record.get("input_dna_length")

            for orf_id, feature in features.items():
                location = feature.get("location") or {}
                try:
                    interval = normalise_orf_interval(
                        int(location["start"]),
                        int(location["end"]),
                        str(location["strand"]),
                        None if record_length is None else int(record_length),
                    )
                except (KeyError, TypeError, ValueError):
                    unusable += 1
                    continue

                rows.append(
                    {
                        "input_id": input_id,
                        "orf_id": orf_id,
                        "genomic_start": interval.start,
                        "genomic_end": interval.end,
                        "genomic_strand": interval.strand,
                    }
                )

    return pd.DataFrame(rows, columns=GENOMIC_COLUMNS), unusable


def get_group_ids(metadata: list[dict[str, Any]]) -> np.ndarray:
    """
    Return one group ID per ORF.

    extract_features currently returns input_id in its metadata. This should
    identify the genome/GenBank record and is therefore used as the grouping
    variable.
    """
    groups = []

    for row in metadata:
        input_id = row.get("input_id")
        if input_id is None:
            raise KeyError(
                "Feature metadata does not contain input_id; genome-level "
                "cross-validation cannot be performed safely."
            )
        groups.append(str(input_id))

    return np.asarray(groups)


def make_model(args: argparse.Namespace, fold: int) -> XGBRFClassifier:
    return XGBRFClassifier(
        n_estimators=500,
        max_depth=8,
        subsample=0.80,
        colsample_bynode=0.80,
        objective="binary:logistic",
        eval_metric="logloss",
        tree_method="hist",
        device=args.device,
        random_state=args.seed + fold,
        n_jobs=-1,
    )


def generate_oof_predictions(
    X: np.ndarray,
    y: np.ndarray,
    metadata: list[dict[str, Any]],
    feature_names: list[str],
    args: argparse.Namespace,
) -> pd.DataFrame:
    groups = get_group_ids(metadata)
    unique_groups = np.unique(groups)

    if len(unique_groups) < args.folds:
        raise ValueError(
            f"Requested {args.folds} folds but found only "
            f"{len(unique_groups)} distinct genomes"
        )

    splitter = GroupKFold(n_splits=args.folds)

    probabilities = np.full(len(y), np.nan, dtype=float)
    predicted_labels = np.full(len(y), -1, dtype=int)
    fold_numbers = np.full(len(y), -1, dtype=int)

    for fold, (train_indices, test_indices) in enumerate(
        splitter.split(X, y, groups),
        start=1,
    ):
        train_groups = np.unique(groups[train_indices])
        test_groups = np.unique(groups[test_indices])

        print(
            f"Fold {fold}/{args.folds}: "
            f"{len(train_indices):,} training ORFs from "
            f"{len(train_groups):,} genomes; "
            f"{len(test_indices):,} testing ORFs from "
            f"{len(test_groups):,} genomes",
            flush=True,
        )

        model = make_model(args, fold)
        model.fit(X[train_indices], y[train_indices])

        fold_probabilities = model.predict_proba(X[test_indices])[:, 1]

        probabilities[test_indices] = fold_probabilities
        predicted_labels[test_indices] = (
            fold_probabilities >= 0.5
        ).astype(int)
        fold_numbers[test_indices] = fold

    if np.isnan(probabilities).any():
        raise RuntimeError("Some ORFs did not receive an out-of-fold prediction")

    result = pd.DataFrame(metadata).reset_index(drop=True)

    feature_frame = pd.DataFrame(
        X,
        columns=feature_names,
    ).reset_index(drop=True)

    # Avoid duplicate in_genbank columns if it occurs in both inputs.
    feature_frame = feature_frame.drop(
        columns=["in_genbank"],
        errors="ignore",
    )

    result = pd.concat([result, feature_frame], axis=1)

    result["actual_label"] = y.astype(int)
    result["in_genbank"] = y.astype(bool)
    result["probability_in_genbank"] = probabilities
    result["predicted_label"] = predicted_labels
    result["fold"] = fold_numbers

    return result


def genomic_overlap(
    first_start: int,
    first_end: int,
    second_start: int,
    second_end: int,
) -> int:
    """
    Return overlap length for zero-based, half-open genomic intervals.

    This remains valid if start/end arrive in reverse order because the
    coordinates are normalised first.
    """
    first_left, first_right = sorted((int(first_start), int(first_end)))
    second_left, second_right = sorted((int(second_start), int(second_end)))

    return max(
        0,
        min(first_right, second_right) - max(first_left, second_left),
    )


def interval_length(start: int, end: int) -> int:
    """Return the length of a zero-based, half-open genomic interval."""
    return abs(int(end) - int(start))


def find_overlapping_annotated_orfs(
    predictions: pd.DataFrame,
) -> pd.DataFrame:
    """
    For every unannotated ORF, find its most relevant overlapping annotated ORF.

    The selected competitor is the annotated ORF with the greatest nucleotide
    overlap. Ties are resolved in favour of the annotated ORF with the lowest
    predicted coding probability.

    Overlaps are computed on the normalised zero-based, half-open genomic axis
    supplied by ``collect_genomic_intervals``. ORFs with no normalised interval
    are excluded rather than compared in raw ``get_orfs`` coordinates.
    """
    required = {
        "input_id",
        "orf_id",
        "genomic_start",
        "genomic_end",
        "in_genbank",
        "probability_in_genbank",
    }

    missing = required.difference(predictions.columns)
    if missing:
        raise KeyError(
            f"Prediction table is missing required columns: {sorted(missing)}"
        )

    rows: list[dict[str, Any]] = []

    placed = predictions.dropna(subset=["genomic_start", "genomic_end"])

    for input_id, genome in placed.groupby("input_id", sort=False):
        annotated = genome.loc[genome["in_genbank"]].copy()
        candidates = genome.loc[~genome["in_genbank"]].copy()

        if annotated.empty or candidates.empty:
            continue

        for candidate_index, candidate in candidates.iterrows():
            overlaps: list[tuple[int, float, int, pd.Series]] = []

            candidate_length = interval_length(
                candidate["genomic_start"],
                candidate["genomic_end"],
            )

            for annotated_index, known in annotated.iterrows():
                overlap_nt = genomic_overlap(
                    candidate["genomic_start"],
                    candidate["genomic_end"],
                    known["genomic_start"],
                    known["genomic_end"],
                )

                if overlap_nt == 0:
                    continue

                annotated_length = interval_length(
                    known["genomic_start"],
                    known["genomic_end"],
                )

                shorter_length = min(candidate_length, annotated_length)
                overlap_fraction_shorter = (
                    overlap_nt / shorter_length
                    if shorter_length
                    else 0.0
                )

                overlaps.append(
                    (
                        overlap_nt,
                        float(overlap_fraction_shorter),
                        annotated_index,
                        known,
                    )
                )

            if not overlaps:
                continue

            overlaps.sort(
                key=lambda item: (
                    item[0],
                    item[1],
                    -float(item[3]["probability_in_genbank"]),
                ),
                reverse=True,
            )

            overlap_nt, overlap_fraction, _, competitor = overlaps[0]

            row = candidate.to_dict()
            row.update(
                {
                    "competing_orf_id": competitor["orf_id"],
                    "competing_genomic_start": competitor["genomic_start"],
                    "competing_genomic_end": competitor["genomic_end"],
                    "competing_genomic_strand": competitor.get(
                        "genomic_strand",
                        "",
                    ),
                    "competing_frame": competitor.get("frame", np.nan),
                    "competing_probability": competitor[
                        "probability_in_genbank"
                    ],
                    "overlap_nt": overlap_nt,
                    "overlap_fraction_shorter": overlap_fraction,
                    "probability_difference": (
                        candidate["probability_in_genbank"]
                        - competitor["probability_in_genbank"]
                    ),
                }
            )
            rows.append(row)

    return pd.DataFrame(rows)


def add_candidate_ranking(frame: pd.DataFrame) -> pd.DataFrame:
    """
    Add a transparent prioritisation score.

    Probability remains the dominant term. Longer ORFs receive a modest bonus,
    and ORFs with both start and stop codons receive small supporting bonuses.
    """
    result = frame.copy()

    protein_length = result.get(
        "protein_length",
        pd.Series(0, index=result.index),
    ).fillna(0)

    length_support = np.clip(
        np.log1p(protein_length) / np.log1p(500),
        0,
        1,
    )

    has_start = result.get(
        "has_start_codon",
        pd.Series(0, index=result.index),
    ).astype(float)

    has_stop = result.get(
        "has_stop_codon",
        pd.Series(0, index=result.index),
    ).astype(float)

    result["candidate_rank_score"] = (
        0.85 * result["probability_in_genbank"]
        + 0.10 * length_support
        + 0.025 * has_start
        + 0.025 * has_stop
    )

    return result


def main() -> None:
    args = parse_args()
    args.output_dir.mkdir(parents=True, exist_ok=True)

    files = discover_json_files(args.json_dir)
    print(f"Found {len(files):,} input JSON files")

    records = load_all_records(files)
    print(f"Loaded {len(records):,} usable genome records")

    X, y, feature_names, metadata = extract_features(
        records,
        return_metadata=True,
    )

    if metadata is None:
        raise RuntimeError("extract_features did not return metadata")

    print(f"Extracted {len(X):,} ORFs")
    print(f"Annotated ORFs: {int(np.sum(y == 1)):,}")
    print(f"Unannotated ORFs: {int(np.sum(y == 0)):,}")

    predictions = generate_oof_predictions(
        X,
        y,
        metadata,
        feature_names,
        args,
    )

    intervals, unplaceable = collect_genomic_intervals(records)
    predictions = predictions.merge(
        intervals,
        on=["input_id", "orf_id"],
        how="left",
        validate="one_to_one",
    )

    unplaced = int(predictions["genomic_start"].isna().sum())
    print(
        f"Normalised genomic intervals for "
        f"{len(predictions) - unplaced:,} ORFs"
    )
    if unplaceable or unplaced:
        print(
            f"Excluded from overlap analysis: {unplaced:,} predicted ORFs "
            f"without a normalised interval "
            f"({unplaceable:,} serialised ORFs could not be normalised)"
        )

    all_output = args.output_dir / "all_orf_oof_predictions.parquet"
    predictions.to_parquet(all_output, index=False)
    print(f"Wrote {all_output}")

    unannotated = predictions.loc[
        (~predictions["in_genbank"])
        & (
            predictions["probability_in_genbank"]
            >= args.minimum_probability
        )
        & (
            predictions["protein_length"]
            >= args.minimum_aa_length
        )
    ].copy()

    unannotated = add_candidate_ranking(unannotated)
    unannotated = unannotated.sort_values(
        [
            "candidate_rank_score",
            "probability_in_genbank",
            "protein_length",
        ],
        ascending=[False, False, False],
    )

    missed_output = args.output_dir / "ranked_putative_missing_orfs.tsv.gz"
    unannotated.to_csv(
        missed_output,
        sep="\t",
        index=False,
        compression="gzip",
    )
    print(f"Wrote {len(unannotated):,} candidates to {missed_output}")

    alternatives = find_overlapping_annotated_orfs(predictions)

    if not alternatives.empty:
        alternatives = alternatives.loc[
            (
                alternatives["probability_in_genbank"]
                >= args.minimum_probability
            )
            & (
                alternatives["competing_probability"]
                <= args.maximum_annotated_probability
            )
            & (
                alternatives["probability_difference"]
                >= args.minimum_probability_difference
            )
            & (
                alternatives["protein_length"]
                >= args.minimum_aa_length
            )
        ].copy()

        # Prioritise probability contrast, then overlap and ORF probability.
        alternatives["replacement_rank_score"] = (
            0.50 * alternatives["probability_in_genbank"]
            + 0.35 * alternatives["probability_difference"]
            + 0.15 * alternatives["overlap_fraction_shorter"]
        )

        alternatives = alternatives.sort_values(
            [
                "replacement_rank_score",
                "probability_difference",
                "overlap_fraction_shorter",
                "protein_length",
            ],
            ascending=[False, False, False, False],
        )

    replacement_output = (
        args.output_dir / "ranked_overlapping_gene_replacements.tsv.gz"
    )
    alternatives.to_csv(
        replacement_output,
        sep="\t",
        index=False,
        compression="gzip",
    )
    print(
        f"Wrote {len(alternatives):,} replacement candidates to "
        f"{replacement_output}"
    )

    summary = {
        "input_files": len(files),
        "genome_records": len(records),
        "orfs": len(predictions),
        "annotated_orfs": int(predictions["in_genbank"].sum()),
        "unannotated_orfs": int((~predictions["in_genbank"]).sum()),
        "orfs_without_genomic_interval": unplaced,
        "serialised_orfs_not_normalisable": unplaceable,
        "high_probability_unannotated_orfs": len(unannotated),
        "high_priority_overlapping_replacements": len(alternatives),
        "minimum_probability": args.minimum_probability,
        "maximum_annotated_probability": (
            args.maximum_annotated_probability
        ),
        "minimum_probability_difference": (
            args.minimum_probability_difference
        ),
        "minimum_aa_length": args.minimum_aa_length,
        "folds": args.folds,
    }

    summary_output = args.output_dir / "candidate_summary.json"
    summary_output.write_text(
        json.dumps(summary, indent=2) + "\n",
        encoding="utf-8",
    )
    print(f"Wrote {summary_output}")


if __name__ == "__main__":
    main()
